"""empty message

Revision ID: 027ef9d96877
Revises: 14148c7d511e
Create Date: 2020-07-21 14:28:13.019350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027ef9d96877'
down_revision = '14148c7d511e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=20), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_key')
    # ### end Alembic commands ###
